### ISSUE TITLE
cordova-icon fails when installed globally after PR #114

### ISSUE THREAD

**Issue by amanojeremie** [AlexDisler/cordova-icon#115]
Receiving the following error on Ubuntu 16.04 with cordova-icon 0.12.0 installed globally
`Error: Cannot find module '../../platforms/android/cordova/version'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at getAndroidFolder (/usr/lib/node_modules/cordova-icon/index.js:28:16)
    at getPlatforms (/usr/lib/node_modules/cordova-icon/index.js:89:17)
    at atLeastOnePlatformFound (/usr/lib/node_modules/cordova-icon/index.js:322:3)
    at Object.<anonymous> (/usr/lib/node_modules/cordova-icon/index.js:377:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)`

**Comment by TouchForDiffusion** [comment]
Same for me

**Comment by AlexDisler** [comment]
Reverted
